# Generated by Django 5.0.6 on 2024-06-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medidor', models.IntegerField()),
                ('dueño', models.CharField(default='', max_length=100)),
                ('fecha_instalacion', models.DateField()),
                ('lote', models.IntegerField()),
                ('manzana', models.IntegerField()),
            ],
        ),
    ]
