# Generated by Django 5.0.6 on 2024-06-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_loteo_remove_medidor_id_alter_medidor_medidor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidor',
            name='consumo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medidor',
            name='lectura_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medidor',
            name='lectura_anterior',
            field=models.IntegerField(default=0),
        ),
    ]
