# Generated by Django 5.0.6 on 2024-06-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0004_alter_medidor_dueño_alter_medidor_fecha_instalacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidor',
            name='medidor',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
