# Generated by Django 5.0.6 on 2024-06-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0006_rename_dueño_medidor_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidor',
            name='fecha_instalacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
