# Generated by Django 5.0.6 on 2024-06-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0007_alter_medidor_fecha_instalacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidor',
            name='lote',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='manzana',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
