# Generated by Django 5.0.6 on 2024-06-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0008_alter_medidor_lote_alter_medidor_manzana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidor',
            name='lectura_actual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='lectura_anterior',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
