# Generated by Django 5.0.6 on 2024-06-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0009_alter_medidor_lectura_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidor',
            name='is_modificate',
            field=models.BooleanField(default=False),
        ),
    ]
